import { Thread } from "@/app/(main)/post/postData";

export const INITIAL_THREADS: Thread[] = [
  {
    id: "1",
    title: "Is there a real hiring slowdown in Bangalore for remote developers?",
    excerpt: "Seeing a lot of mixed signals in the ecosystem. Local Indian startups are offering roughly 30-40% lower compensation packages compared to last year's peaks, but global remote firms seem to still hire aggressively with EU/US parity budgets. How are you navigating interviews right now?",
    author: {
      name: "Amit Sharma",
      avatar: "AS",
      role: "Staff Engineer",
      reputation: 420,
    },
    category: "Career Prep",
    tags: ["career", "remote-jobs", "bangalore"],
    upvotes: 48,
    commentsCount: 22,
    views: 312,
    timeAgo: "2 hours ago",
  },
  {
    id: "2",
    title: "Why we migrated our Next.js 15 site back to native CSS variables from custom build tooling",
    excerpt: "Tailwind v4 is fantastic for core design systems, but we hit complex specificity overrides in hybrid server/client dynamic styles. Switching our theme bindings entirely to simple, native CSS variables solved specificity bugs, speeded up reload builds, and made theme switching 100% synchronous.",
    author: {
      name: "Priya Patel",
      avatar: "PP",
      role: "Frontend Lead",
      reputation: 380,
    },
    category: "Tech & Architecture",
    tags: ["nextjs", "css", "frontend"],
    upvotes: 62,
    commentsCount: 17,
    views: 405,
    timeAgo: "5 hours ago",
  },
  {
    id: "3",
    title: "React 19 Server Actions vs Express APIs: What are Indian tech companies adopting in 2026?",
    excerpt: "For fresh greenfield setups, Next Server Actions are incredibly fast to scaffold and keep types safe. However, large enterprise codebases in Gurgaon/Bengaluru still mandate standard Express REST/gRPC backends. Let's debate the scaling overheads and developer experiences.",
    author: {
      name: "Rajesh Kumar",
      avatar: "RK",
      role: "CTO, ChaiTech",
      reputation: 512,
    },
    category: "Tech & Architecture",
    tags: ["react19", "node", "architecture"],
    upvotes: 39,
    commentsCount: 31,
    views: 290,
    timeAgo: "1 day ago",
  },
  {
    id: "4",
    title: "How to negotiate a 50LPA+ package as an IC (Individual Contributor) without entering management?",
    excerpt: "Let's demystify the IC track in India. You do not have to migrate to engineering management to cross the 40-50LPA compensation boundary. Here is a full breakdown of the skills, technical interview positioning, and portfolio projects that landed my current IC role.",
    author: {
      name: "Karan Johar",
      avatar: "KJ",
      role: "Principal Architect",
      reputation: 640,
    },
    category: "Career Prep",
    tags: ["career", "salary", "leadership"],
    upvotes: 89,
    commentsCount: 45,
    views: 870,
    timeAgo: "2 days ago",
  },
  {
    id: "5",
    title: "Understanding Database Sharding: A practical guide for System Design Interviews",
    excerpt: "Sharding is frequently mentioned as a silver bullet in high-level interviews. But dividing tables horizontally introduces major architectural pain points: cross-shard joins, transaction consistency, and key imbalances. Let's analyze the exact tradeoffs of sharding MySQL vs PostgreSQL.",
    author: {
      name: "Neha Krishnan",
      avatar: "NK",
      role: "Database Architect",
      reputation: 295,
    },
    category: "Tech & Architecture",
    tags: ["systemdesign", "database"],
    upvotes: 54,
    commentsCount: 19,
    views: 340,
    timeAgo: "3 days ago",
  },
];
